server:
  port: 8081

spring:
  config:
    import: file:env.properties
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: ${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: ${REDIRECT_URI}
            scope:
              - email
              - profile

# AWS S3
access:
  key:
    id: ${AWS_ACCESS}
    secret: ${AWS_SECRET}

s3:
  region:
    name: ${S3_REGION}
  bucket:
    name: ${S3_BUCKET}
  path:
    featured_images: ${S3_PATH_FEATURED_IMAGES}

logging:
  level:
    org.springframework.web.client.ResTemplate: DEBUG

application:
  auth:
    secretKey: ${JWT_SECRET_KEY}
    expiration: 86400000 # a day
    refresh-token:
      expiration: 604800000 # 7 days
  cors:
    allowedOrigins: ${FE_BASE_URL},${BE_BASE_URL}
  oauth2:
    authorizedRedirectUris:
      - ${OAUTH2_AUTHORIZED_REDIRECT_URIS}
